services:
  - type: web
    name: autohire-api
    runtime: node
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 869568422226-14fcbs1j1esdl1f0phijfhoude5il7qk.apps.googleusercontent.com
